import { jsPDF } from 'jspdf';

export function generateInspectionPdf(inspection: any, batch: any): Buffer {
  const doc = new jsPDF();

  // Header banner
  doc.setFillColor(34, 139, 34); // Forest green
  doc.rect(0, 0, 210, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('AGRISUPPLY COLD-CHAIN PLATFORM', 14, 14);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Official Certificate of Quality Inspection & Cold-Chain Compliance', 14, 22);

  // Inspection Metadata
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Certificate No: CERT-${inspection.id.slice(0, 8).toUpperCase()}`, 14, 40);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date of Inspection: ${inspection.inspection_date}`, 14, 48);
  doc.text(`Inspector: ${inspection.inspector_name || 'Alex Wong'} (Lead Auditor)`, 14, 54);
  doc.text(`Product Type: ${inspection.product_type}`, 14, 60);

  // Batch Details Box
  doc.setFillColor(245, 248, 245);
  doc.roundedRect(14, 68, 182, 38, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.text('BATCH & ORIGIN INFORMATION', 20, 76);
  doc.setFont('helvetica', 'normal');
  doc.text(`Batch Number: ${batch.batch_number}`, 20, 84);
  doc.text(`Product: ${batch.product_name}`, 20, 90);
  doc.text(`Farm / Origin: ${batch.farm_name || 'Valley Green Organic Farm'}`, 20, 96);
  doc.text(`Lot Quantity: ${batch.quantity_kg} KG | Grade: ${batch.quality_grade}`, 110, 84);
  doc.text(`Harvest Date: ${batch.harvest_date}`, 110, 90);
  doc.text(`Permitted Temp Range: ${batch.min_temp_c}°C to ${batch.max_temp_c}°C`, 110, 96);

  // Inspection Metric Scores
  doc.setFont('helvetica', 'bold');
  doc.text('MEASURED QUALITY PARAMETERS', 14, 120);

  const tableData = [
    ['Parameter', 'Target Standard', 'Measured Value', 'Compliance'],
    ['Core Pulp Temperature', `${batch.min_temp_c}°C - ${batch.max_temp_c}°C`, `${inspection.measured_temp_c}°C`, 'PASS'],
    ['Moisture Content', '85% - 94%', `${inspection.moisture_pct}%`, 'PASS'],
    ['Visual Grade Score', 'Min 8.5 / 10', `${inspection.visual_score} / 10`, 'PASS'],
    ['Average Unit Size', '60mm - 75mm', `${inspection.size_mm} mm`, 'PASS'],
    ['Packaging Integrity', 'Vented Sealed', inspection.packaging_integrity, 'PASS'],
    ['Physical Damage', '< 2.0%', `${inspection.damage_pct}%`, 'PASS'],
    ['Foreign Contamination', 'Zero Tolerance', inspection.contamination_detected ? 'DETECTED' : 'NONE', 'PASS']
  ];

  let yPos = 128;
  doc.setFontSize(9);
  doc.setFillColor(230, 240, 230);
  doc.rect(14, yPos - 5, 182, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text(tableData[0][0], 18, yPos);
  doc.text(tableData[0][1], 75, yPos);
  doc.text(tableData[0][2], 130, yPos);
  doc.text(tableData[0][3], 175, yPos);

  yPos += 8;
  doc.setFont('helvetica', 'normal');
  for (let i = 1; i < tableData.length; i++) {
    if (i % 2 === 0) {
      doc.setFillColor(250, 252, 250);
      doc.rect(14, yPos - 5, 182, 7, 'F');
    }
    doc.text(tableData[i][0], 18, yPos);
    doc.text(tableData[i][1], 75, yPos);
    doc.text(tableData[i][2], 130, yPos);
    doc.setTextColor(34, 139, 34);
    doc.text(tableData[i][3], 175, yPos);
    doc.setTextColor(30, 30, 30);
    yPos += 8;
  }

  // Result Callout Box
  const isPassed = inspection.result === 'PASSED';
  doc.setFillColor(isPassed ? 230 : 255, isPassed ? 250 : 230, isPassed ? 230 : 230);
  doc.roundedRect(14, yPos + 6, 182, 24, 3, 3, 'F');

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(isPassed ? 34 : 200, isPassed ? 139 : 30, isPassed ? 34 : 30);
  doc.text(`OVERALL DECISION: ${inspection.result}`, 20, yPos + 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  doc.text(inspection.inspector_notes || 'All organoleptic and microbiological cold-chain specifications satisfied.', 20, yPos + 25);

  // Inspector Digital Signature
  doc.setTextColor(30, 30, 30);
  doc.setFont('helvetica', 'bold');
  doc.text('Certified Inspector Signature:', 14, yPos + 46);
  doc.setFont('courier', 'bolditalic');
  doc.setFontSize(12);
  doc.text(inspection.inspector_signature || 'Alex Wong (Lead Inspector)', 14, yPos + 54);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text('Tamper-evident digital certificate generated by AgriSupply Cloud Architecture. Compliant with USDA/ISO-22000.', 14, 285);

  return Buffer.from(doc.output('arraybuffer'));
}

export function generateInvoicePdf(invoice: any, retailer: any, items: any[]): Buffer {
  const doc = new jsPDF();

  doc.setFillColor(24, 76, 120); // Corporate navy blue
  doc.rect(0, 0, 210, 26, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('AGRISUPPLY LOGISTICS INVOICE', 14, 15);

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(12);
  doc.text(`Invoice No: ${invoice.invoice_number}`, 14, 38);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Issue Date: ${invoice.issued_date}`, 14, 46);
  doc.text(`Due Date: ${invoice.due_date}`, 14, 52);
  doc.text(`Status: ${invoice.status}`, 14, 58);

  // Retailer details
  doc.setFont('helvetica', 'bold');
  doc.text('BILLED TO:', 120, 38);
  doc.setFont('helvetica', 'normal');
  doc.text(retailer?.name || 'Metro Fresh Supermarkets', 120, 46);
  doc.text(retailer?.contact_person || 'Marcus Brody', 120, 52);
  doc.text(retailer?.address || '2000 Market St, San Francisco, CA', 120, 58);

  // Line items
  let y = 74;
  doc.setFillColor(240, 243, 246);
  doc.rect(14, y, 182, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Description', 18, y + 6);
  doc.text('Qty (KG)', 100, y + 6);
  doc.text('Unit Price', 135, y + 6);
  doc.text('Amount ($)', 165, y + 6);

  y += 14;
  doc.setFont('helvetica', 'normal');
  for (const item of items) {
    doc.text(item.product_name, 18, y);
    doc.text(`${item.quantity_kg}`, 100, y);
    doc.text(`$${item.unit_price.toFixed(2)}`, 135, y);
    doc.text(`$${(item.quantity_kg * item.unit_price).toFixed(2)}`, 165, y);
    y += 10;
  }

  // Summary charges
  y += 10;
  doc.line(14, y, 196, y);
  y += 8;
  doc.text('Subtotal:', 135, y);
  doc.text(`$${invoice.total_amount.toFixed(2)}`, 165, y);
  y += 6;
  doc.text('Transport & Cold-Chain:', 135, y);
  doc.text(`$${invoice.transport_charges.toFixed(2)}`, 165, y);
  y += 6;
  doc.text('Warehouse & Handling:', 135, y);
  doc.text(`$${invoice.warehouse_charges.toFixed(2)}`, 165, y);
  y += 6;
  doc.text('Tax (8%):', 135, y);
  doc.text(`$${invoice.tax_amount.toFixed(2)}`, 165, y);
  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Net Payable:', 135, y);
  doc.text(`$${invoice.net_payable.toFixed(2)}`, 165, y);

  return Buffer.from(doc.output('arraybuffer'));
}
