export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN',
  FARMER: 'FARMER',
  FARM_MANAGER: 'FARM_MANAGER',
  QUALITY_INSPECTOR: 'QUALITY_INSPECTOR',
  TRANSPORT_MANAGER: 'TRANSPORT_MANAGER',
  DRIVER: 'DRIVER',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  RETAILER: 'RETAILER',
  FINANCE_OFFICER: 'FINANCE_OFFICER'
} as const;

export const PIPELINE_STAGES = [
  'NEW',
  'QUALITY_CHECK',
  'APPROVED',
  'READY',
  'IN_TRANSIT',
  'WAREHOUSE',
  'PROCESSING',
  'DISPATCHED',
  'DELIVERED'
] as const;
